services:
    odiseo_sylius_vendor_plugin.controller.vendor_slug:
        class: Odiseo\SyliusVendorPlugin\Controller\VendorSlugController
        public: true
        calls:
            - setContainer: ['@service_container']
