services:
    odiseo_sylius_vendor_plugin.event_listener.admin.menu_builder:
        class: Odiseo\SyliusVendorPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    odiseo_sylius_vendor_plugin.menu_builder.admin.vendor_form:
        class: Odiseo\SyliusVendorPlugin\Menu\VendorFormMenuBuilder
        arguments:
            - '@knp_menu.factory'
            - '@event_dispatcher'
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: odiseo_sylius_vendor_plugin.admin.vendor_form }

    odiseo_sylius_vendor_plugin.block_event_listener.layout.vendor.javascripts:
        class: Odiseo\SyliusVendorPlugin\Block\VendorJsBlockListener
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.admin.layout.javascripts, method: onBlockEvent }

    odiseo_sylius_vendor_plugin.event_listener.vendor_aware_listener:
        class: Odiseo\SyliusVendorPlugin\Mapping\VendorAwareListener
        arguments:
            - '@sylius.resource_registry'
            - '%odiseo_sylius_vendor_plugin.model.vendor.class%'
            - '%sylius.model.product.class%'
            - '%sylius.model.channel.class%'
        tags:
            - { name: doctrine.event_subscriber, connection: default, priority: 99 }

    odiseo_sylius_vendor_plugin.event_listener.vendor_logo_upload:
        class: Odiseo\SyliusVendorPlugin\EventListener\VendorLogoUploadListener
        arguments:
            - '@odiseo_sylius_vendor_plugin.uploader.vendor_logo'
        tags:
            - { name: kernel.event_listener, event: odiseo_sylius_vendor_plugin.vendor.pre_create, method: uploadLogo }
            - { name: kernel.event_listener, event: odiseo_sylius_vendor_plugin.vendor.pre_update, method: uploadLogo }
