services:
    odiseo_sylius_vendor_plugin.sitemap_provider.vendor:
        class: Odiseo\SyliusVendorPlugin\SitemapProvider\VendorUrlProvider
        arguments:
            - '@odiseo_sylius_vendor_plugin.repository.vendor'
            - '@router'
            - '@sylius.sitemap_url_factory'
            - '@sylius.context.locale'
            - '@sylius.context.channel'
        tags:
            - { name: sylius.sitemap_provider }
